print("School: <Haas Hall Academy>")
print("Team Member 1: <Jack> <Hare>")
print("Team Member 2: <Yahya> <sridjajametra>")
print("Team Member 3: <Praket> <Gauri>")
print("Sponsor: <Margaret> <Cotton>")